## Contexto de la Historia
Eres parte de un equipo de científicos de datos que ha descubierto un laboratorio de investigación abandonado. El laboratorio contiene datos cruciales sobre un importante proyecto científico, pero todos los sistemas están bloqueados con puzzles basados en NumPy. Tienes 60 minutos para recuperar los datos antes de que el sistema de autodestrucción se active.

### Nivel 1: "La Puerta de Entrada"
**Escenario**: Para abrir la puerta principal, necesitas demostrar tu conocimiento básico de NumPy.

**Desafío 1** (3 minutos):
```python
# La contraseña es la suma de todos los números pares en este array
array_secreto = np.array([1, 4, 7, 12, 15, 18, 21, 24])
# Debes usar máscaras booleanas de NumPy para encontrarla
```

In [1]:
import numpy as np

In [3]:
array_secreto = np.array([1, 4, 7, 12, 15, 18, 21, 24])

In [7]:
mascara = np.mod(array_secreto,2) == 0
respuesta = np.sum(array_secreto[mascara])
respuesta

58

### Nivel 2: "La Sala de Matrices"
**Escenario**: Has entrado en una sala llena de pantallas mostrando matrices.

**Desafío 2** (5 minutos):
```python
# Crea una matriz 3x3 que cuando se multiplique por sí misma
# produzca el siguiente resultado:
resultado = np.array([[1, 0, 0],
                     [0, 4, 0],
                     [0, 0, 9]])
```

In [11]:
resultado = np.array([[1, 0, 0],
                     [0, 4, 0],
                     [0, 0, 9]])

In [15]:
matriz = np.sqrt(resultado)
matriz

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

In [19]:
respuesta = matriz * matriz
respuesta

array([[1., 0., 0.],
       [0., 4., 0.],
       [0., 0., 9.]])

### Nivel 3: "El Laboratorio de Datos"
**Escenario**: Encuentras un conjunto de datos experimentales que necesitan ser procesados.

**Desafío 3** (7 minutos):
```python
# Los datos están corrompidos. Necesitas:
# 1. Reemplazar todos los valores negativos por 0
# 2. Normalizar los datos entre 0 y 1
# 3. Encontrar la media de cada columna
datos_corrompidos = np.array([
    [-2, 15, 8, -5],
    [10, -8, 3, 12],
    [4, 5, -1, 9]
])
```

In [21]:
datos_corrompidos = np.array([
    [-2, 15, 8, -5],
    [10, -8, 3, 12],
    [4, 5, -1, 9]
])

In [23]:
datos_limpios = np.clip(datos_corrompidos, 0, None)

In [33]:
datos_norm = (datos_limpios - datos_limpios.min()) / (datos_limpios.max() - datos_limpios.min())
datos_norm

array([[0.        , 1.        , 0.53333333, 0.        ],
       [0.66666667, 0.        , 0.2       , 0.8       ],
       [0.26666667, 0.33333333, 0.        , 0.6       ]])

In [37]:
medias = np.mean(datos_norm, axis = 0)
medias

array([0.31111111, 0.44444444, 0.24444444, 0.46666667])

### Nivel 4: "La Cámara Final"
**Escenario**: Has llegado a la cámara que contiene los datos cruciales.

**Desafío 4** (10 minutos):
```python
# Debes reorganizar esta matriz 1D en una matriz 3D
# que represente un cubo RGB de 2x2x3
datos_finales = np.array([255, 0, 0, 0, 255, 0,
                         0, 0, 255, 255, 255, 255])
# El resultado debe tener la forma (2, 2, 3)
```

In [39]:
datos_finales = np.array([
    255, 0, 0,   # Rojo
    0, 255, 0,   # Verde
    0, 0, 255,   # Azul
    255, 255, 255
])

In [41]:
colores_rgb = datos_finales.reshape(2,2,3)
print(colores_rgb)

[[[255   0   0]
  [  0 255   0]]

 [[  0   0 255]
  [255 255 255]]]


In [49]:
numeros = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
num = numeros.reshape(3,3,2)
num

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

##### Sistema de Puntuación
- Completar sin pistas: 100 puntos por nivel
- Usar primera pista: -20 puntos
- Usar segunda pista: -20 puntos adicionales
- Tiempo restante: +1 punto por minuto
