In [ ]:
##Cargando los datos de cáncer de mama de la librería Sckit-learn
from sklearn.datasets import load_breast_cancer


In [ ]:

cancer = load_breast_cancer()
print (cancer['feature_names']) # cada característica es un tipo de medida com, tamaño, radio, textura, suavidad
print (cancer['data']) #los valores de cada característica del conjunto de datos de cáncer de mama


print (cancer.target_names)

print (cancer['data'])
## Los valores de cada característica del conjunto de datos de cáncer de mama

print (cancer.target_names)
## Hay 2 clases, maligno o benigno

['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']
[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
['malignant' 'benign']
[[1.799e+01 1.

Muestra un ejemplo de clasificación de SVM (Support Vector Machines) para el cáncer
de mama. Primero carga la función load_breast_cancer() de los datos de cáncer de
mama y luego coloca los datos en un formato DataFrame, utiliza los datos de
características como X y el objetivo con¡mo Y, y utiliza traint_test_split() para dividir X e
y en conjuntos de entrenamiento y prueba. Específicamente, el 80% de datos son para
entrenamiento y el 20% para pruebas. Utiliza los datos de entrenamiento X_train e
y_train para entrenar el SVM y usa los datos de prueba X_test para predicciones.
Finalmente, imprime la matriz de confusión y el informe de clasificación.

In [12]:
#importamos librerias necesarias
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

print("\nForma de los datos", cancer.data.shape)

#imprimir las primeras filas de los datos
print("\n", cancer.data[0:5])



#imprimier las primeras etiquetas de los datos
print("\n", cancer.target)

X = cancer.data #todas las caracteristicas
y = cancer.target #todas las etiquetas

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

clf = SVC()
clf.fit(X_train, y_train)

#Realizar predicciones
predictions = clf.predict(X_test)

#imprimir matriz de confusion y reporte de clasificacion
cm = np.array(confusion_matrix(y_test, predictions, labels=[0,1]))
confusion = pd.DataFrame(cm, index=['es_cancer', 'esta sano'], 
                         columns['predicted_cancer', 'predicted_healthy'])

print("\nmatriz de confusion\n", confusion )
                         
                         

SyntaxError: positional argument follows keyword argument (674811391.py, line 32)